### ISSUE TITLE
Menu Color Is Linked To Knob LED Color

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#3]
When we updated the LED for the knobs to be green, it also affected the menu. We need to seperate these color so that the menu can be white like the rest of the theme.

I've @mentioned the coders that have volunteered to assist with coding for this theme. I know you're all busy, but if you have time, I would really appreciate some assistance on this.

@Umcaruje 
@tresf 
@diizy 
@Sti2nd

**Comment by Umcaruje** [comment]
Can you please name the specific CSS property you want split, and what should the new CSS property be called and what parts of the program it should affect.

**Comment by tresf** [comment]
@RebeccaDeField I'm with @Umcaruje here.  Which property are you using which is causing the described problem?  If you tell us that, it will help us figure out why they're linked and then we can propose a code solution upstream.

**Comment by RebeccaDeField** [comment]
Okay, so I did a bit of examining to find the code that was effecting the menu/knobs. It's under the LmmsPalette section.

```
qproperty-windowText: #1de276;
```

So it seems like the knob LED is linked to the menu text color, whereas I thought it was the other way around. We will need to just asign a seperate color for the knobs and I will change the text color back to white.

![text](https://cloud.githubusercontent.com/assets/7960169/11262234/9c2f76c6-8e31-11e5-9699-d101be5da6c2.png)

![untitled](https://cloud.githubusercontent.com/assets/7960169/11262235/a098f520-8e31-11e5-91d3-6f7974631571.png)

**Comment by tresf** [comment]
Thanks @RebeccaDeField.

I spent quite a while trying to track down the cause of this and this is what I found.... (C++ stuff)
- In order to use `Q_PROPERTIES` for custom stylesheets, your class needs to [inherit `QObject` and  also call the `Q_OBJECT` macro](http://doc.qt.io/qt-5/properties.html)
- The class which contains the track `VOL` and `PAN` knobs are (I think) contained in [`trackSettingsWidget`](https://github.com/LMMS/lmms/blob/master/include/Track.h#L57) which uses an inline `typedef` declaration an no `Q_OBJECT` macros.
- Since the class which contains the Knobs isn't exposed, it can't inherit the `qproperty-foo` settings that it needs, which -- if implemented -- should be identical in usage to overrides like [`TripleOscillatorView Knob`](https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L545:L553) which are currently working just fine.
- Without access to override these knob styles, you're forced to use application-wide style settings (such as the aforementioned `LmmsPalette`, which obviously is undesired. 

So, I think to fix this is just a matter of getting someone familiar with `QObject` inheritance and then add the appropriate style blocks to style.css.

@michaelgregorius any chance you can help?

**Comment by michaelgregorius** [comment]
@tresf I had a look at the code. I don't know whether I interpret your findings correctly.

To make things more clear I have first removed the `typedef` for `trackSettingsWidget` and replaced the two occurrences with `QWidget`. The knobs in question (created in `InstrumentTrackView::InstrumentTrackView`) have `m_trackSettingsWidget` set as their parent which in turn is a bland `QObject`. The parent of the `m_trackSettingsWidget` is a `TrackView`. So with regards to the types the parent child relationship is:

```
TrackView > QObject > Knob
```

So, do I understand correctly that the problem with regards to the CSS is that the parent of the `Knob` is a `QObject` and that therefore it is not possible to address the two specific knobs in the track?

For testing I have tried the following in the CSS but it did not work:

``` CSS
TrackView > QObject > Knob {
        background: rgba(255,0,0, 128);
}
```

If the `QObject` is in fact the problem a solution might be to introduce a new class `TrackSettingsWidget` and to use this so that it can be addressed in the CSS.

**Comment by tresf** [comment]
From my studies, Knob was taking on properties properly in our plugins as a member variable of its parent object.

I think your questions are around class inheritance. I think I accidentally suggested this with the word "parent", but perhaps "owner" or "instantiator" would have been a better description.

All speculative though... I'm not very familiar with this, personally.

**Comment by RebeccaDeField** [comment]
@michaelgregorius Is there any way that you could lend some assistance on this issue or is it a dead-end?

**Comment by michaelgregorius** [comment]
@RebeccaDeField I had another look and the problem should be fixed with the pull request LMMS/lmms#2680. After this fix has been merged into master you should be able to style the lines of the knobs with the following style sheet snippet:

``` CSS
TrackView Knob {
    qproperty-lineColor: rgb(255, 0, 0);
}
```

It seems that I have looked in the wrong direction during my previous investigations. The problem simply was that the knobs in the instrument and sample tracks are of type `knobSmall_17` which used a hard coded palette colors to draw the line in the knob drawing code (example `QApplication::palette().color( QPalette::Active, QPalette::WindowText )`). The aforementioned fix also fixes the problem for all other knob types.

**Comment by RebeccaDeField** [comment]
@michaelgregorius Awesome, thanks!

I think this issue can be closed now?

**Comment by michaelgregorius** [comment]
@RebeccaDeField I would keep this issue open until the pull request is merged into master and you have checked whether it works for you.

**Comment by RebeccaDeField** [comment]
@michaelgregorius Sounds like a plan :)

**Comment by michaelgregorius** [comment]
@RebeccaDeField I have just merged the fix into master. You can now check if the fix works for you.

**Comment by RebeccaDeField** [comment]
@michaelgregorius Just tested this. Works perfectly!
