### ISSUE TITLE
Clean-Up And Delete Unused Icons...

### ISSUE THREAD

**Issue by RebeccaDeField** [HDDigitizerMusic/lmms-alt-theme#6]
We need to delete the icons that are no longer in use. I know that the `Freeze` icon is no longer being used, but I'm asumming there are several others that are still in the icons folder.

These have not been deleted already, I'm not sure if there is a reason why, so I didn't want to go ahead and start deleting things. If there is not a reason for this, then I just need to know the names of the icons that I no longer being used so that I can delete them.

I've @mentioned the coders that have volunteered to assist with coding for this theme. I know you're all busy, but if you have time, I would really appreciate some assistance on this.

@Umcaruje 
@tresf 
@diizy 
@Sti2nd

**Comment by tresf** [comment]
> I didn't want to go ahead and start deleting things

Please go ahead and start deleting things that are known to not be in use.  Leftover cruft is a mistake. :+1: 

In regards to coding, @Sti2nd and @diizy haven't been extremely active lately and myself and @Umcaruje are quite busy, so it may take some time for some of these items.

Last, I really don't like doing this on @HDDigitizerMusic's repo.  He left the project high and dry on several items and I have no sense of trust working from this location.

**Comment by RebeccaDeField** [comment]
@tresf  I understand you guys are busy, so no pressure. I just wanted to get these in front of the people that want to help so that you can when you have time.

As for working with Digitizer, it's too bad that you feel that way. I have been working very closely with him the whole time. He has made huge contributions to this theme, he was the one who came up with the idea in the first place, and I have worked with him on many other projects. I witnessed the way he was being treated by some of the users, which is why he chose to move on after he had finished the work that he had committed to.

I don't see how any problems could emerge with how things are setup. If anything, this can be a good opportunity to build some trust and mend bridges.

**Comment by tresf** [comment]
>  I witnessed the way he was being treated by some of the users, which is why he chose to move on after he had finished the work that he had committed to.

I'd rather not use the internet as a public location to stir up the past, but this is not personal.  He didn't finish his work, so I'm not sure what that statement is in regards to.  I won't beat the topic up further, but I wanted a full disclaimer that past items were never settled.  It's your hard work and determination bringing us here, and we do so feeling a bit of unease.

**Comment by RebeccaDeField** [comment]
Since this is a separate project I agree that it would be best to keep the threads on topic.

I welcome anyone who is willing to contribute to this project, and as much as I would really love to get your help because of how skilled you are, if you don't like the way things are setup on this repo, it's completely your choice if you want contribute or not. That being said, I am not planning on changing the setup for this repo. I hope that we can move forward now, without any problems.

Of course, there are still many things I have left to do, but I am very excited with how far this has come. I have just recently committed a lot of updates to the artwork and more are coming. :)

**Comment by tresf** [comment]
:+1:

**Comment by tresf** [comment]
@RebeccaDeField here are my findings.

@michaelgregorius @Umcaruje @StakeoutPunch a spot-check is greatly appreciated.

Some special considerations:
- Some of these were tricky because they use counters or dynamic filenames such as `knob01` and `note_tripletquarter`.
- Some pixmaps are only used for plugins and some are used by multiple plugins.  It's arguable that they should be moved or cloned into their respective plugin locations, but the decision to completely decouple our internal plugins is a conversation for another day IMO.

Ok... here it is... 

| PIXMAP | IN-USE |
| --- | --- |
| add_automation | :white_check_mark: |
| add_bb_track | :white_check_mark: |
| add_folder | :white_check_mark: |
| add | :white_check_mark: |
| add_sample_track | :white_check_mark: |
| analysis | :white_check_mark: |
| apply | :white_check_mark: |
| Apply-selected | :white_check_mark: |
| arp_down | :white_check_mark: |
| arp_free | :white_check_mark: |
| arp_random | :white_check_mark: |
| arp_sort | :white_check_mark: |
| arp_sync | :white_check_mark: |
| arp_up_and_down | :white_check_mark: |
| arp_up | :white_check_mark: |
| automation | :white_check_mark: |
| automation_track | :white_check_mark: |
| autoscroll_off | :white_check_mark: |
| autoscroll_on | :white_check_mark: |
| background_artwork | :white_check_mark: |
| back_to_start | :white_check_mark: |
| back_to_zero | :white_check_mark: |
| bb_track_btn | :white_check_mark: |
| bb_track | :white_check_mark: |
| black_key | :white_check_mark: |
| black_key_pressed | :white_check_mark: |
| cancel | :white_check_mark: |
| chord | :white_check_mark: |
| clock | :white_check_mark: |
| colorize | :white_check_mark: |
| combobox_arrow | :white_check_mark: |
| combobox_arrow_selected | :white_check_mark: |
| combobox_bg | :white_check_mark: |
| computer | :white_check_mark: |
| controller | :white_check_mark: |
| cpuload_bg | :white_check_mark: |
| cpuload_leds | :white_check_mark: |
| dont_know | :white_check_mark: |
| drum | :no_entry: |
| edit_copy | :white_check_mark: |
| edit_cut | :white_check_mark: |
| edit_draw | :white_check_mark: |
| edit_erase | :white_check_mark: |
| edit_move | :white_check_mark: |
| edit_paste | :white_check_mark: |
| edit_redo | :white_check_mark: |
| edit_rename | :white_check_mark: |
| edit_select | :white_check_mark: |
| edit_undo | :white_check_mark: |
| effect_plugin | :white_check_mark: |
| envelope_graph | :white_check_mark: |
| error | :white_check_mark: |
| exit | :white_check_mark: |
| exp_wave_active | :white_check_mark: |
| exp_wave_inactive | :white_check_mark: |
| factory_files | :white_check_mark: |
| fader_background | :white_check_mark: |
| fader_knob | :white_check_mark: |
| fader_leds | :white_check_mark: |
| filter_2lp | :white_check_mark: |
| filter_ap | :white_check_mark: |
| filter_bp | :white_check_mark: |
| filter_hp | :white_check_mark: |
| filter_lp | :white_check_mark: |
| filter_notch | :white_check_mark: |
| flip_x | :white_check_mark: |
| flip_y | :white_check_mark: |
| folder_locked | :white_check_mark: |
| folder_opened | :white_check_mark: |
| folder | :white_check_mark: |
| freeze | :no_entry: |
| frozen | :no_entry: |
| fx_mixer | :white_check_mark: |
| hand | :white_check_mark: |
| help | :white_check_mark: |
| hint | :white_check_mark: |
| home | :white_check_mark: |
| hq_mode | :white_check_mark: |
| icon | :white_check_mark: |
| instrument_track | :white_check_mark: |
| keep_stop_position | :white_check_mark: |
| knob01 | :white_check_mark: |
| knob02 | :white_check_mark: |
| knob03 | :white_check_mark: |
| knob04 | :white_check_mark: |
| knob05 | :white_check_mark: |
| lcd_19green | :white_check_mark: |
| lcd_19red | :white_check_mark: |
| lcd_21pink | :white_check_mark: |
| led_green | :white_check_mark: |
| led_off | :white_check_mark: |
| led_red | :white_check_mark: |
| led_yellow | :white_check_mark: |
| lfo_controller_artwork | :white_check_mark: |
| lfo_d100_active | :white_check_mark: |
| lfo_d100_inactive | :white_check_mark: |
| lfo_graph | :white_check_mark: |
| lfo_x100_active | :white_check_mark: |
| lfo_x100_inactive | :white_check_mark: |
| lfo_x1_active | :white_check_mark: |
| lfo_x1_inactive | :white_check_mark: |
| loop_point_b | :white_check_mark: |
| loop_point_e | :white_check_mark: |
| loop_points_off | :white_check_mark: |
| loop_points_on | :white_check_mark: |
| main_slider | :white_check_mark: |
| master_pitch | :white_check_mark: |
| master_volume | :white_check_mark: |
| metronome | :white_check_mark: |
| midi_file | :white_check_mark: |
| mixer_send_off | :white_check_mark: |
| mixer_send_on | :white_check_mark: |
| moog_saw_wave_active | :white_check_mark: |
| moog_saw_wave_inactive | :white_check_mark: |
| muted | :white_check_mark: |
| new_channel | :white_check_mark: |
| note_double_whole | :white_check_mark: |
| note_eighth | :white_check_mark: |
| note_half | :white_check_mark: |
| note_none | :white_check_mark: |
| note | :white_check_mark: |
| note_quarter | :white_check_mark: |
| note_sixteenth | :white_check_mark: |
| note_thirtysecond | :white_check_mark: |
| note_tripleteighth | :white_check_mark: |
| note_triplethalf | :white_check_mark: |
| note_tripletquarter | :white_check_mark: |
| note_tripletsixteenth | :white_check_mark: |
| note_tripletthirtysecond | :white_check_mark: |
| note_whole | :white_check_mark: |
| output_graph | :white_check_mark: |
| pat_rec | :white_check_mark: |
| pause | :white_check_mark: |
| piano | :white_check_mark: |
| play | :white_check_mark: |
| playpos_marker | :white_check_mark: |
| plugins | :white_check_mark: |
| ports | :white_check_mark: |
| pr_black_key | :white_check_mark: |
| pr_black_key_pressed | :white_check_mark: |
| preset_file | :white_check_mark: |
| progression_cubic_hermite | :white_check_mark: |
| progression_discrete | :white_check_mark: |
| progression_linear | :white_check_mark: |
| project_export | :white_check_mark: |
| project_file | :white_check_mark: |
| project_import | :white_check_mark: |
| project_new_from_template | :white_check_mark: |
| project_new | :white_check_mark: |
| project_notes | :white_check_mark: |
| project_open_down | :no_entry: |
| project_open | :white_check_mark: |
| project_open_recent | :white_check_mark: |
| project_saveas | :white_check_mark: |
| project_save | :white_check_mark: |
| pr_white_key_big | :white_check_mark: |
| pr_white_key_big_pressed | :white_check_mark: |
| pr_white_key_small | :white_check_mark: |
| pr_white_key_small_pressed | :white_check_mark: |
| quantize | :white_check_mark: |
| random_wave_active | :white_check_mark: |
| random_wave_inactive | :white_check_mark: |
| receive_bg_arrow | :white_check_mark: |
| record_accompany | :white_check_mark: |
| record | :white_check_mark: |
| reload | :white_check_mark: |
| round_square_wave_active | :white_check_mark: |
| round_square_wave_inactive | :white_check_mark: |
| sample_file | :white_check_mark: |
| sample_track | :white_check_mark: |
| saw_wave_active | :white_check_mark: |
| saw_wave_inactive | :white_check_mark: |
| sbarrow_down_d | :white_check_mark: |
| sbarrow_down | :white_check_mark: |
| sbarrow_left_d | :white_check_mark: |
| sbarrow_left | :white_check_mark: |
| sbarrow_right_d | :white_check_mark: |
| sbarrow_right | :white_check_mark: |
| sbarrow_up_d | :white_check_mark: |
| sbarrow_up | :white_check_mark: |
| scale | :white_check_mark: |
| send_bg_arrow | :white_check_mark: |
| setup_audio | :white_check_mark: |
| setup_directories | :white_check_mark: |
| setup_general | :white_check_mark: |
| setup_midi | :white_check_mark: |
| setup_performance | :white_check_mark: |
| sin_wave_active | :white_check_mark: |
| sin_wave_inactive | :white_check_mark: |
| songeditor | :white_check_mark: |
| soundfont_file | :white_check_mark: |
| splash | :white_check_mark: |
| square_wave_active | :white_check_mark: |
| square_wave_inactive | :white_check_mark: |
| step_btn_add | :white_check_mark: |
| step_btn_duplicate | :white_check_mark: |
| step_btn_off_light | :white_check_mark: |
| step_btn_off | :white_check_mark: |
| step_btn_on_100 | :white_check_mark: |
| step_btn_on | :no_entry: |
| step_btn_on_yellow | :white_check_mark: |
| step_btn_remove | :white_check_mark: |
| stepper-down | :white_check_mark: |
| stepper-down-press | :no_entry: |
| stepper-left | :white_check_mark: |
| stepper-left-press | :white_check_mark: |
| stepper-right | :white_check_mark: |
| stepper-right-press | :white_check_mark: |
| stepper-up | :white_check_mark: |
| stepper-up-press | :white_check_mark: |
| stop | :white_check_mark: |
| tempo_sync | :white_check_mark: |
| text_block | :white_check_mark: |
| text_bold | :white_check_mark: |
| text_center | :white_check_mark: |
| text_italic | :white_check_mark: |
| text_left | :white_check_mark: |
| text_right | :white_check_mark: |
| text_under | :white_check_mark: |
| trackop_c | :white_check_mark: |
| track_op_grip | :white_check_mark: |
| trackop_h | :white_check_mark: |
| track_op_menu_active | :white_check_mark: |
| track_op_menu | :white_check_mark: |
| trackop | :white_check_mark: |
| triangle_wave_active | :white_check_mark: |
| triangle_wave_inactive | :white_check_mark: |
| uhoh | :white_check_mark: |
| unavailable_sound | :white_check_mark: |
| unfreeze | :no_entry: |
| unknown_file | :white_check_mark: |
| usr_wave_active | :white_check_mark: |
| usr_wave_inactive | :white_check_mark: |
| vst_plugin_file | :white_check_mark: |
| whatsthis | :white_check_mark: |
| white_key | :white_check_mark: |
| white_key_pressed | :white_check_mark: |
| white_noise_wave_active | :white_check_mark: |
| white_noise_wave_inactive | :white_check_mark: |
| zoom | :white_check_mark: |
| zoom_x | :white_check_mark: |
| zoom_y | :white_check_mark: |

**Comment by michaelgregorius** [comment]
Here is an overview of all the pixmaps that are marked as unused above:

| Name | Icon |
| --- | --- |
| drum | ![drum](https://cloud.githubusercontent.com/assets/9293269/11168298/390b376e-8b8a-11e5-998a-54c416a46748.png) |
| freeze | ![freeze](https://cloud.githubusercontent.com/assets/9293269/11168300/5277ab92-8b8a-11e5-92a6-bbb24875f971.png) |
| frozen | ![frozen](https://cloud.githubusercontent.com/assets/9293269/11168301/56642d0c-8b8a-11e5-83ae-c6f00ee07d9c.png) |
| project_open_down | ![project_open_down](https://cloud.githubusercontent.com/assets/9293269/11168307/715a9754-8b8a-11e5-9794-b79ca0e4a390.png) |
| step_btn_on | ![step_btn_on](https://cloud.githubusercontent.com/assets/9293269/11168313/94848320-8b8a-11e5-87b6-0be9eef83cd6.png) |
| stepper-down-press | ![stepper-down-press](https://cloud.githubusercontent.com/assets/9293269/11168314/9cc00d70-8b8a-11e5-8aea-82f3553e7c03.png) |
| unfreeze | ![unfreeze](https://cloud.githubusercontent.com/assets/9293269/11168317/a59c3112-8b8a-11e5-8575-c0e4b9ede86e.png) |

I think we should remove them in case no one identifies one or more of them as being used somewhere.

**Comment by RebeccaDeField** [comment]
Thank you for such comprehensive work! :+1: 

I will delete these on this fork. We should probably delete them from the `default` theme as well.

**Comment by tresf** [comment]
> I will delete these on this fork. We should probably delete them from the default theme as well.

We can cherry-pick the commit once you've completed it, just file a bug upstream and we'll pull the changes in.  Alternately we can do them manually, but it is important that a change like this makes it upstream. :+1:

**Comment by Umcaruje** [comment]
I'm against removing the `stepper-down-press` icon, since if `stepper-down` is used somewhere, `stepper-down-press` should be used when that button is clicked.

**Comment by RebeccaDeField** [comment]
@Umcaruje I have no problem with keeping that one if you feel that it is important.
